source "https://github.com/CocoaPods/Specs.git"

platform :ios, "8.0"
use_frameworks!

target "ZLSwiftFM" do

pod 'SnapKit', '~> 3.1.2'
pod 'Kingfisher', '~> 3.2.4'
pod 'Alamofire', '~> 4.2.0'
pod 'SwiftyJSON', '~> 3.1.3'

end
